name = "ps-price-tracker"
main = "src/worker.js"
compatibility_date = "2026-08-22"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ps-price-tracker"
database_id = "fe6b9f5f-ad5f-40a0-984a-668d6bf570a9"
migrations_dir = "migrations"